artifacts_root: artifacts

ingest_from_sql:
  root_dir: artifacts/data-ingestion
  loan_default_table: loan_default
  loan_default_path: artifacts/data-ingestion/Loan_default.csv
  
dump_data:
  root_dir: artifacts/data
  input_train_path: "artifacts/data/X_train.pkl"
  input_test_path: "artifacts/data/X_test.pkl"
  output_train_path: "artifacts/data/y_train.pkl"
  output_test_path: "artifacts/data/y_test.pkl"

encoded_data:
  root_dir: artifacts/preprocessing
  encoded_train_path: "artifacts/preprocessing/X_train_encoded.pkl"
  encoded_test_path: "artifacts/preprocessing/X_test_encoded.pkl"
  encoder_model_path: "artifacts/models/encoder.pkl"
  scaler_model_path: "artifacts/models/scaler.pkl"

train_model:
  root_dir: "artifacts/models"
  model_path: "artifacts/models/logistic_regression.pkl"

train_evaluation:
  root_dir: "artifacts/models"
  score_path: metrics/scores.json
  mlflow_dataset_path: "artifacts/data/train_eval_result.csv"
  mlflow_dataset_column:
  - "LoanID"
  - "Age"
  - "Income"
  - "LoanAmount"
  - "MonthsEmployed"
  - "NumCreditLines"
  - "InterestRate"
  - "LoanTerm"
  - "DTIRatio"
  - "Education"
  - "EmploymentType"
  - "MaritalStatus"
  - "HasMortgage"
  - "HasDependents"
  - "LoanPurpose"
  - "HasCoSigner"
  - "Default"
  - "predictions"
  mlflow_exp_name: "Loan Default Classification"
  mlflow_run_name: "train-eval-default"

  predict:
  root_dir: "artifacts/predict"
  mlflow_model_name: "logistic_regression"
  mlflow_encoder_model_path: "encoder/encoder.pkl"
  mlflow_scaler_model_path: "scaler/scaler.pkl"

unit_test:
  root_dir: "artifacts/test"
  mlflow_input_example_path: "models/input_example.json"